---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  become: true
  vars:
    nginx_vhosts:
      - listen: "80 http"
        server_name: "example.com"
        server_name_redirect: "www.example.com"
        root: "/var/www/example.com"
        index: "index.php index.html index.htm"
        error_page: ""
        access_log: ""
        error_log: ""
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "example.com.conf"

  tasks:
    - name: installnginx
      include_role:
        name: geerlingguy.nginx